// Build configuration for the custom config UI (Preact + TypeScript).
//
// Output is a SINGLE self-contained homebridge-ui/public/index.html: an HTML
// fragment with the JS and CSS inlined. config-ui-x inlines the fragment
// into the <body> of a generated wrapper document served inside an iframe;
// its Content-Security-Policy permits inline scripts/styles (the wrapper
// itself relies on them) but blocks all external hosts, so inlining is the
// most robust delivery across config-ui-x versions and works fully offline.
import { fileURLToPath } from 'node:url';

import { defineConfig, type Plugin } from 'vite';

const uiDir = fileURLToPath(new URL('.', import.meta.url));
const outDir = fileURLToPath(new URL('../homebridge-ui/public', import.meta.url));

/** Collapse the built chunks/assets into one inline index.html fragment. */
function inlineFragment(): Plugin {
  return {
    name: 'mqttthing-inline-fragment',
    // run after Vite's internal css-post plugin has emitted the CSS asset
    enforce: 'post',
    generateBundle(_options, bundle) {
      let js = '';
      let css = '';
      for (const [fileName, output] of Object.entries(bundle)) {
        if (output.type === 'chunk') {
          js += output.code;
        } else if (fileName.endsWith('.css')) {
          css += String(output.source);
        }
        delete bundle[fileName];
      }
      // '</script' inside JS string/regex literals would end the inline
      // <script> element early; escape it (valid, equivalent JS).
      const safeJs = js.replace(/<\/script/gi, '<\\/script');
      const fragment = [
        '<!-- homebridge-mqttthing-ex custom config UI (generated by `npm run build:ui`; do not edit) -->',
        '<style>',
        css.trim(),
        '</style>',
        '<div id="mqttthing-ui"></div>',
        '<script type="module">',
        safeJs.trim(),
        '</script>',
        '',
      ].join('\n');
      this.emitFile({ type: 'asset', fileName: 'index.html', source: fragment });
    },
  };
}

export default defineConfig({
  root: uiDir,
  esbuild: {
    jsx: 'automatic',
    jsxImportSource: 'preact',
  },
  build: {
    outDir,
    emptyOutDir: true,
    target: 'es2020',
    sourcemap: false,
    cssCodeSplit: false,
    rollupOptions: {
      input: fileURLToPath(new URL('./src/main.tsx', import.meta.url)),
      output: {
        entryFileNames: 'bundle.js',
        assetFileNames: 'bundle[extname]',
      },
    },
  },
  plugins: [inlineFragment()],
});
